[[redirects]]
  from = "/2023/*"
  to = "https://fourthinncafa.netlify.app/:splat"
  status = 301

[[redirects]]
  from = "/2024/"
  to = "/2024/"
  status = 301

[[redirects]]
  from = "/"
  to = "/2025"
  status = 301  