[[redirects]]
  from = "/2023/*"
  to = "https://fourthinncafa.netlify.app/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/2024/:splat"
  status = 301

[[redirects]]
  from = "/2025/*"
  to = "/2025/:splat"
  status = 301  